spring:
  application:
    name: config-server
  cloud:
    config:
      label: main
      server:
        git:
          uri: https://github.com/yuanfengcaichen/cloud_version/
          searchPaths: demo_respo
          default-label: main
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/